[devConfig]
title = hollogram.io INSIDER BUILD API
description = Be social, stay anonymous. - Made with love 🩵🩷🤍🩷🩵
version = 24.12
terms_of_use = Hollogram INSIDER BUILD
url_list = [{"url":"http://127.0.0.1:8000","description":"Staging Environment"},{"url":"https://api.budgi.net","description":"Testing Environment"},{"url":"https://api.hollogram.io","description":"Production Environment"}]
[config]
ip = 0.0.0.0
port = 8000
;auto_reload -- True|False - Allows the software to reload automatically instead of needing to be killed and restarted manually.
auto_reload = True
;debug -- True|False
debug = True
host = localhost
